/*  BEGIN_FILE_HDR
********************************************************************************
*   File Name       : Dem_Cfg.c
********************************************************************************
*   Project/Product : AUTOSAR BSW PROJECT
*   Title           : Dem module configuration File
*   Author          : Hirain
********************************************************************************
*   Description     : Dem module configuration File
*
********************************************************************************
*   Limitations     : None
*
********************************************************************************
*
********************************************************************************
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------  ----------   ---------------
*   V1.0.2_3.5.5_AZ240046       09/05/2024    Eas           N/A          N/A
*
********************************************************************************
* END_FILE_HDR*/

/*******************************************************************************
*   Include files
*******************************************************************************/
#include "Dem_Lcfg.h"
#include "Rte_Dem.h"
#include "NvM_Cfg.h"

/*******************************************************************************
*   Dem Container:DemGeneral
*******************************************************************************/
#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


/*DemOperationCycle*/
CONST(Dem_OperationCycleInfoType, DEM_CONST) Dem_OperationCycleTable[DEM_NUM_OF_OPCYCLE] =
{
    {FALSE, FALSE, Dem_OpCycle_DemOperationCycle, DEM_OPCYC_IGNITION}
};

/*DemEnableCondition*/
CONST(Dem_EnableConditionType, DEM_CONST) Dem_EnConditionTable[DEM_NUM_OF_EN_CONDITION] =
{
    {0, FALSE},
    {1, FALSE},
    {2, FALSE},
    {3, TRUE},
    {4, FALSE}
};

/*DemEnableConditionGroup*/
CONST(uint8, DEM_CONST) Dem_EnableConditionRef_Array_0[4] = {0, 1, 2, 3};
CONST(uint8, DEM_CONST) Dem_EnableConditionRef_Array_1[4] = {0, 1, 2, 4};
CONST(Dem_EnableConditionGroupType, DEM_CONST) Dem_EnConditionGroupTable[DEM_NUM_OF_EN_GROUP] =
{
    {4, Dem_EnableConditionRef_Array_0},
    {4, Dem_EnableConditionRef_Array_1}
};

/*DemNvRamBlockId*/
CONST(Dem_NvRamBlockIdType, DEM_CONST) Dem_NvRamBlockIdTable[DEM_NUM_OF_BLOCKID] =
{
    {NvM_Block_Dem}
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"

#define DEM_START_SEC_CONFIG_DATA_32
#include "MemMap.h"


/*DemGroupOfDTC*/
CONST(Dem_DTCGroupType, DEM_CONST) Dem_GroupOfDTCTable[DEM_NUM_OF_DTCGROUP] =
{
    DEM_DTC_GROUP_ALL
};

#define DEM_STOP_SEC_CONFIG_DATA_32
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_8
#include "MemMap.h"

/*DemFreezeFrameRecNumClass*/
CONST(uint8, DEM_CONST) Dem_FFRecClassRef_Array_0[2] = {0, 1};

#define DEM_STOP_SEC_CONFIG_DATA_8
#include "MemMap.h"

#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"

CONST(Dem_FreezeFrameRecNumClassType, DEM_CONST) Dem_FFRecNumClassTable[DEM_NUM_OF_FFRECNUM] =
{
    {2, Dem_FFRecClassRef_Array_0}
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_8
#include "MemMap.h"

/*DemFreezeFrameRecordClass*/
CONST(uint8, DEM_CONST) Dem_DidClassRef_Array_0[5] = {0, 1, 2, 3, 4};
CONST(uint8, DEM_CONST) Dem_DidClassRef_Array_1[5] = {0, 1, 2, 3, 4};

#define DEM_STOP_SEC_CONFIG_DATA_8
#include "MemMap.h"

#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"

CONST(Dem_FreezeFrameRecordClassType, DEM_CONST) Dem_FFRecClassTable[DEM_NUM_OF_FFRECCLASS] =
{
    {0x10, DEM_TRIGGER_ON_CONFIRMED, DEM_UPDATE_RECORD_NO, 5, Dem_DidClassRef_Array_0},
    {0x0, DEM_TRIGGER_ON_CONFIRMED, DEM_UPDATE_RECORD_YES, 5, Dem_DidClassRef_Array_1}
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_8
#include "MemMap.h"

/*DemDidClass*/
CONST(uint8, DEM_CONST) Dem_FFDataElementClassRef_Array_0[1] = {0};
CONST(uint8, DEM_CONST) Dem_FFDataElementClassRef_Array_1[1] = {1};
CONST(uint8, DEM_CONST) Dem_FFDataElementClassRef_Array_2[1] = {2};
CONST(uint8, DEM_CONST) Dem_FFDataElementClassRef_Array_3[1] = {3};
CONST(uint8, DEM_CONST) Dem_FFDataElementClassRef_Array_4[1] = {4};

#define DEM_STOP_SEC_CONFIG_DATA_8
#include "MemMap.h"

#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"

CONST(Dem_DidClassType, DEM_CONST) Dem_DidClassTable[DEM_NUM_OF_DID] =
{
    {1, Dem_FFDataElementClassRef_Array_0, 0x4F01},
    {1, Dem_FFDataElementClassRef_Array_1, 0x4F02},
    {1, Dem_FFDataElementClassRef_Array_2, 0x4F03},
    {1, Dem_FFDataElementClassRef_Array_3, 0x4F04},
    {1, Dem_FFDataElementClassRef_Array_4, 0x4F05}
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


/*DemDataElementClass*/
CONST(Dem_InternalDataElementClassType, DEM_CONST) Dem_IntDataElement_0 =
{
    1, DEM_OCCCTR
};
CONST(Dem_InternalDataElementClassType, DEM_CONST) Dem_IntDataElement_1 =
{
    1, DEM_AGED_COUNTER
};
CONST(Dem_InternalDataElementClassType, DEM_CONST) Dem_IntDataElement_2 =
{
    1, DEM_AGINGCTR_UPCNT
};
CONST(Dem_ExternalCSDataElementClassType, DEM_CONST) Dem_CSDataElement_0 =
{
    1, Dem_Rte_DataElement_0x4F01_EcuVoltage_ReadDataElement, TRUE
};
CONST(Dem_ExternalCSDataElementClassType, DEM_CONST) Dem_CSDataElement_1 =
{
    1, Dem_Rte_DataElement_0x4F02_TotalMileage_ReadDataElement, TRUE
};
CONST(Dem_ExternalCSDataElementClassType, DEM_CONST) Dem_CSDataElement_2 =
{
    6, Dem_Rte_DataElement_0x4F03_LocalTimeSignal_ReadDataElement, TRUE
};
CONST(Dem_ExternalCSDataElementClassType, DEM_CONST) Dem_CSDataElement_3 =
{
    2, Dem_Rte_DataElement_0x4F04_VehicleSpeed_ReadDataElement, TRUE
};
CONST(Dem_ExternalCSDataElementClassType, DEM_CONST) Dem_CSDataElement_4 =
{
    1, Dem_Rte_DataElement_0x4F05_ReadyState_ReadDataElement, TRUE
};
CONST(Dem_ExternalCSDataElementClassType, DEM_CONST) Dem_CSDataElement_5 =
{
    1, Dem_Rte_DataElement_Priority_ReadDataElement, TRUE
};
CONST(Dem_DataElementClassType, DEM_CONST) Dem_DataElementClassTable[DEM_NUM_OF_DATA] =
{
    {
        NULL_PTR,
        &Dem_CSDataElement_0
    },
    {
        NULL_PTR,
        &Dem_CSDataElement_1
    },
    {
        NULL_PTR,
        &Dem_CSDataElement_2
    },
    {
        NULL_PTR,
        &Dem_CSDataElement_3
    },
    {
        NULL_PTR,
        &Dem_CSDataElement_4
    },
    {
        &Dem_IntDataElement_0,
        NULL_PTR
    },
    {
        &Dem_IntDataElement_1,
        NULL_PTR
    },
    {
        &Dem_IntDataElement_2,
        NULL_PTR
    },
    {
        NULL_PTR,
        &Dem_CSDataElement_5
    }
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_8
#include "MemMap.h"

/*DemExtendedDataClass*/
CONST(uint8, DEM_CONST) Dem_ExtDataRecClassRef_Array_0[4] = {0, 1, 2, 3};

#define DEM_STOP_SEC_CONFIG_DATA_8
#include "MemMap.h"

#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"

CONST(Dem_ExtendedDataClassType, DEM_CONST) Dem_ExtDataClassTable[DEM_NUM_OF_EXTDATACLASS] =
{
    {4, Dem_ExtDataRecClassRef_Array_0}
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_8
#include "MemMap.h"

/*DemExtendedDataRecordClass*/
CONST(uint8, DEM_CONST) Dem_ExtDataElementClassRef_Array_0[1] = {5};
CONST(uint8, DEM_CONST) Dem_ExtDataElementClassRef_Array_1[1] = {6};
CONST(uint8, DEM_CONST) Dem_ExtDataElementClassRef_Array_2[1] = {7};
CONST(uint8, DEM_CONST) Dem_ExtDataElementClassRef_Array_3[1] = {8};

#define DEM_STOP_SEC_CONFIG_DATA_8
#include "MemMap.h"

#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"

CONST(Dem_ExtendedDataRecordClassType, DEM_CONST) Dem_ExtDataRecClassTable[DEM_NUM_OF_EXTDATAREC] =
{
    {
        1,
        Dem_ExtDataElementClassRef_Array_0,
        0x1,
        DEM_TRIGGER_ON_CONFIRMED,
        DEM_UPDATE_RECORD_NO
    },
    {
        1,
        Dem_ExtDataElementClassRef_Array_1,
        0x2,
        DEM_TRIGGER_ON_CONFIRMED,
        DEM_UPDATE_RECORD_NO
    },
    {
        1,
        Dem_ExtDataElementClassRef_Array_2,
        0x3,
        DEM_TRIGGER_ON_CONFIRMED,
        DEM_UPDATE_RECORD_NO
    },
    {
        1,
        Dem_ExtDataElementClassRef_Array_3,
        0x4,
        DEM_TRIGGER_ON_CONFIRMED,
        DEM_UPDATE_RECORD_NO
    }
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"



/*DemCallbackDTCStatusChangedFnc*/
CONST(Dem_DTCStatusChangedNotificationType, DEM_CONST) Dem_DtcStatusChangedNotificationArray[1] =
{
    Dem_Rte_CallbackDTCStatusChange
};

/*******************************************************************************
*   Dem Container:DemConfigSet
*******************************************************************************/

/*DemEventParameter*/
CONST(Dem_EventParameterType, DEM_CONST) Dem_EventTable[DEM_NUM_OF_EVENT] =
{
    {
        0,
        0,
        0,
        NULL_PTR,
        1,
        Dem_Event_0x940009,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[0]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        1,
        NULL_PTR,
        1,
        Dem_Event_0x94001C,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94001C_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        2,
        NULL_PTR,
        1,
        Dem_Event_0x94001D,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94001D_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        3,
        NULL_PTR,
        1,
        Dem_Event_0x940054,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940054_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        4,
        NULL_PTR,
        1,
        Dem_Event_0x940056,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940056_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        5,
        NULL_PTR,
        1,
        Dem_Event_0x940089,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940089_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        6,
        NULL_PTR,
        1,
        Dem_Event_0x940091,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940091_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        7,
        NULL_PTR,
        1,
        Dem_Event_0x9400A2,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[1]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        8,
        NULL_PTR,
        1,
        Dem_Event_0x9400A3,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[1]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        9,
        NULL_PTR,
        1,
        Dem_Event_0x940109,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[0]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        10,
        NULL_PTR,
        1,
        Dem_Event_0x94011C,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94011C_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        11,
        NULL_PTR,
        1,
        Dem_Event_0x94011D,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94011D_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        12,
        NULL_PTR,
        1,
        Dem_Event_0x940189,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940189_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        13,
        NULL_PTR,
        1,
        Dem_Event_0x9401A3,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[0]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        14,
        NULL_PTR,
        1,
        Dem_Event_0x94021C,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94021C_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        15,
        NULL_PTR,
        1,
        Dem_Event_0x940254,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940254_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        16,
        NULL_PTR,
        1,
        Dem_Event_0x940306,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940306_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        17,
        NULL_PTR,
        1,
        Dem_Event_0x94031C,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94031C_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        18,
        NULL_PTR,
        1,
        Dem_Event_0x940354,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        19,
        NULL_PTR,
        1,
        Dem_Event_0x940406,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940406_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        20,
        NULL_PTR,
        1,
        Dem_Event_0x94041C,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94041C_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        21,
        NULL_PTR,
        1,
        Dem_Event_0x940498,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940498_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        22,
        NULL_PTR,
        1,
        Dem_Event_0x9404A2,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x9404A2_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        23,
        NULL_PTR,
        1,
        Dem_Event_0x940504,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940504_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        24,
        NULL_PTR,
        1,
        Dem_Event_0x940506,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940506_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        25,
        NULL_PTR,
        1,
        Dem_Event_0x94051C,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94051C_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        26,
        NULL_PTR,
        1,
        Dem_Event_0x940604,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940604_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        27,
        NULL_PTR,
        1,
        Dem_Event_0x940606,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940606_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        28,
        NULL_PTR,
        1,
        Dem_Event_0x94061C,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x94061C_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        29,
        NULL_PTR,
        1,
        Dem_Event_0x940704,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940704_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        30,
        NULL_PTR,
        1,
        Dem_Event_0x940706,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940706_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        31,
        NULL_PTR,
        1,
        Dem_Event_0x940709,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[0]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        32,
        NULL_PTR,
        1,
        Dem_Event_0x940754,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940754_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        33,
        NULL_PTR,
        1,
        Dem_Event_0x940804,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940804_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        34,
        NULL_PTR,
        1,
        Dem_Event_0x940854,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940854_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        35,
        NULL_PTR,
        1,
        Dem_Event_0x940904,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940904_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        36,
        NULL_PTR,
        1,
        Dem_Event_0x940A04,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940A04_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        37,
        NULL_PTR,
        1,
        Dem_Event_0x940B04,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x940B04_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        38,
        NULL_PTR,
        1,
        Dem_Event_0x942009,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        39,
        NULL_PTR,
        1,
        Dem_Event_0x942209,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        40,
        NULL_PTR,
        1,
        Dem_Event_0x942309,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        41,
        NULL_PTR,
        1,
        Dem_Event_0x942409,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        42,
        NULL_PTR,
        1,
        Dem_Event_0x942509,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        43,
        NULL_PTR,
        1,
        Dem_Event_0x942609,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        44,
        NULL_PTR,
        1,
        Dem_Event_0x942D09,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        45,
        NULL_PTR,
        1,
        Dem_Event_0x942F09,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        46,
        NULL_PTR,
        1,
        Dem_Event_0x943009,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0x943009_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        47,
        NULL_PTR,
        1,
        Dem_Event_0xD20008,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20008_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        48,
        NULL_PTR,
        1,
        Dem_Event_0xD20086,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        49,
        NULL_PTR,
        1,
        Dem_Event_0xD20087,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20087_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        50,
        NULL_PTR,
        1,
        Dem_Event_0xD20108,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20108_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        51,
        NULL_PTR,
        1,
        Dem_Event_0xD20186,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        52,
        NULL_PTR,
        1,
        Dem_Event_0xD20187,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20187_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        53,
        NULL_PTR,
        1,
        Dem_Event_0xD20208,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20208_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        54,
        NULL_PTR,
        1,
        Dem_Event_0xD20286,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        55,
        NULL_PTR,
        1,
        Dem_Event_0xD20287,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20287_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        56,
        NULL_PTR,
        1,
        Dem_Event_0xD20288,
        DEM_EVENT_KIND_BSW,
        FALSE,
        0,
        DEM_REPORT_BEFORE_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20288_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        57,
        NULL_PTR,
        1,
        Dem_Event_0xD20308,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20308_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        58,
        NULL_PTR,
        1,
        Dem_Event_0xD20386,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        59,
        NULL_PTR,
        1,
        Dem_Event_0xD20387,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20387_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        60,
        NULL_PTR,
        1,
        Dem_Event_0xD20388,
        DEM_EVENT_KIND_BSW,
        FALSE,
        0,
        DEM_REPORT_BEFORE_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20388_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        61,
        NULL_PTR,
        1,
        Dem_Event_0xD20408,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20408_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        62,
        NULL_PTR,
        1,
        Dem_Event_0xD20486,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        63,
        NULL_PTR,
        1,
        Dem_Event_0xD20508,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20508_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        64,
        NULL_PTR,
        1,
        Dem_Event_0xD20586,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        65,
        NULL_PTR,
        1,
        Dem_Event_0xD20608,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20608_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        66,
        NULL_PTR,
        1,
        Dem_Event_0xD20686,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        67,
        NULL_PTR,
        1,
        Dem_Event_0xD20708,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20708_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        68,
        NULL_PTR,
        1,
        Dem_Event_0xD20786,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        69,
        NULL_PTR,
        1,
        Dem_Event_0xD20808,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20808_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        70,
        NULL_PTR,
        1,
        Dem_Event_0xD20886,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        71,
        NULL_PTR,
        1,
        Dem_Event_0xD20908,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20908_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        72,
        NULL_PTR,
        1,
        Dem_Event_0xD20986,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        73,
        NULL_PTR,
        1,
        Dem_Event_0xD20A08,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20A08_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        74,
        NULL_PTR,
        1,
        Dem_Event_0xD20A86,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        75,
        NULL_PTR,
        1,
        Dem_Event_0xD20B08,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20B08_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        76,
        NULL_PTR,
        1,
        Dem_Event_0xD20B86,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        77,
        NULL_PTR,
        1,
        Dem_Event_0xD20C08,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20C08_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        78,
        NULL_PTR,
        1,
        Dem_Event_0xD20C86,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        79,
        NULL_PTR,
        1,
        Dem_Event_0xD20D08,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20D08_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        80,
        NULL_PTR,
        1,
        Dem_Event_0xD20D86,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        81,
        NULL_PTR,
        1,
        Dem_Event_0xD20E08,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20E08_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        82,
        NULL_PTR,
        1,
        Dem_Event_0xD20E86,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        83,
        NULL_PTR,
        1,
        Dem_Event_0xD20F08,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD20F08_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        84,
        NULL_PTR,
        1,
        Dem_Event_0xD20F86,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        85,
        NULL_PTR,
        1,
        Dem_Event_0xD21008,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD21008_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        86,
        NULL_PTR,
        1,
        Dem_Event_0xD21087,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD21087_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        87,
        NULL_PTR,
        1,
        Dem_Event_0xD21208,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD21208_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        88,
        NULL_PTR,
        1,
        Dem_Event_0xD21287,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        89,
        NULL_PTR,
        1,
        Dem_Event_0xD21308,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD21308_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        90,
        NULL_PTR,
        1,
        Dem_Event_0xD21387,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        91,
        NULL_PTR,
        1,
        Dem_Event_0xD21408,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD21408_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        92,
        NULL_PTR,
        1,
        Dem_Event_0xD21441,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        93,
        NULL_PTR,
        1,
        Dem_Event_0xD21487,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        94,
        NULL_PTR,
        1,
        Dem_Event_0xD21508,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD21508_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        95,
        NULL_PTR,
        1,
        Dem_Event_0xD21541,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        96,
        NULL_PTR,
        1,
        Dem_Event_0xD21608,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD21608_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        97,
        NULL_PTR,
        1,
        Dem_Event_0xD21708,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD21708_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        98,
        NULL_PTR,
        1,
        Dem_Event_0xD22086,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        99,
        NULL_PTR,
        1,
        Dem_Event_0xD22186,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        100,
        NULL_PTR,
        1,
        Dem_Event_0xD22286,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        101,
        NULL_PTR,
        1,
        Dem_Event_0xD22386,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        102,
        NULL_PTR,
        1,
        Dem_Event_0xD22486,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        103,
        NULL_PTR,
        1,
        Dem_Event_0xD22586,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        104,
        NULL_PTR,
        1,
        Dem_Event_0xD22686,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        105,
        NULL_PTR,
        1,
        Dem_Event_0xD22786,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        106,
        NULL_PTR,
        1,
        Dem_Event_0xD22787,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        107,
        NULL_PTR,
        1,
        Dem_Event_0xD22887,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        108,
        NULL_PTR,
        1,
        Dem_Event_0xD22987,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            &(Dem_DebounceCounterBasedClassTable[1]),
            NULL_PTR,
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        109,
        NULL_PTR,
        1,
        Dem_Event_0xD23087,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD23087_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        110,
        NULL_PTR,
        1,
        Dem_Event_0xD23187,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD23187_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        111,
        NULL_PTR,
        1,
        Dem_Event_0xD23287,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD23287_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        112,
        NULL_PTR,
        1,
        Dem_Event_0xD23387,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD23387_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        113,
        NULL_PTR,
        1,
        Dem_Event_0xD23487,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD23487_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        114,
        NULL_PTR,
        1,
        Dem_Event_0xD23587,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD23587_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        115,
        NULL_PTR,
        1,
        Dem_Event_0xD23687,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        {
            NULL_PTR,
            NULL_PTR,
            Dem_Rte_Event_0xD23687_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    }
};

/*DemDTC*/
CONST(Dem_DTCInfoType, DEM_CONST) Dem_DTCTable[DEM_NUM_OF_DTC] =
{
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940009,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94001C,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94001D,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940054,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940056,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940089,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940091,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9400A2,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9400A3,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940109,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94011C,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94011D,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940189,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9401A3,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94021C,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940254,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940306,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94031C,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940354,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940406,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94041C,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940498,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9404A2,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940504,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940506,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94051C,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940604,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940606,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x94061C,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940704,
    },
    {
        2,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940706,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940709,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940754,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940804,
    },
    {
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940854,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940904,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940A04,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x940B04,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x942009,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x942209,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x942309,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x942409,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x942509,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x942609,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x942D09,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x942F09,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x943009,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20008,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20086,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20087,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20108,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20186,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20187,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20208,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20286,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20287,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20288,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20308,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20386,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20387,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20388,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20408,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20486,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20508,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20586,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20608,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20686,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20708,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20786,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20808,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20886,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20908,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20986,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20A08,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20A86,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20B08,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20B86,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20C08,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20C86,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20D08,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20D86,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20E08,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20E86,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20F08,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD20F86,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21008,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21087,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21208,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21287,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21308,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21387,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21408,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21441,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21487,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21508,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21541,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21608,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD21708,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22086,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22186,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22286,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22386,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22486,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22586,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22686,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22786,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22787,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22887,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD22987,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD23087,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD23187,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD23287,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD23387,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD23487,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD23587,
    },
    {
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xD23687,
    }
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_8
#include "MemMap.h"

/*DemDTCAttributes*/
CONST(uint8, DEM_CONST) Dem_ExtDataClassRef_0 = 0;
CONST(uint8, DEM_CONST) Dem_FFRecNumClassRef_0 = 0;
CONST(uint8, DEM_CONST) Dem_ExtDataClassRef_1 = 0;
CONST(uint8, DEM_CONST) Dem_FFRecNumClassRef_1 = 0;
CONST(uint8, DEM_CONST) Dem_ExtDataClassRef_2 = 0;
CONST(uint8, DEM_CONST) Dem_FFRecNumClassRef_2 = 0;


#define DEM_STOP_SEC_CONFIG_DATA_8
#include "MemMap.h"

#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


CONST(Dem_DTCAttributesType, DEM_CONST) Dem_DTCAttributesTable[DEM_NUM_OF_DTCATB] =
{
    {
        TRUE,
        40,
        1,
        0,
        1,
        DEM_EVENT_SIGNIFICANCE_FAULT,
        32,
        &Dem_ExtDataClassRef_0,
        &Dem_FFRecNumClassRef_0,
        TRUE,
        NULL_PTR,
        0
    },
    {
        TRUE,
        40,
        1,
        0,
        2,
        DEM_EVENT_SIGNIFICANCE_FAULT,
        32,
        &Dem_ExtDataClassRef_1,
        &Dem_FFRecNumClassRef_1,
        TRUE,
        NULL_PTR,
        0
    },
    {
        TRUE,
        40,
        1,
        0,
        1,
        DEM_EVENT_SIGNIFICANCE_FAULT,
        32,
        &Dem_ExtDataClassRef_2,
        &Dem_FFRecNumClassRef_2,
        TRUE,
        NULL_PTR,
        0
    }
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


#define DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"


/*DemDebounceCounterBasedClass*/
CONST(Dem_DebounceCounterBasedClassType, DEM_CONST) Dem_DebounceCounterBasedClassTable[DEM_NUM_OF_COUNTER_BASED] =
{
    {
        DEM_DEBOUNCE_FREEZE,
        10,
        10,
        -30,
        30,
        TRUE,
        TRUE,
        0,
        0,
        FALSE
    },
    {
        DEM_DEBOUNCE_FREEZE,
        1,
        1,
        -1,
        20,
        TRUE,
        TRUE,
        0,
        0,
        FALSE
    }
};

/*DemDebounceTimeBaseClass*/
CONST(Dem_DebounceTimeBaseClassType, DEM_CONST) Dem_DebounceTimeBaseClassTable[DEM_NUM_OF_TIME_BASED] =
{
    {
        DEM_DEBOUNCE_FREEZE,
        1000,
        1000
    },
    {
        DEM_DEBOUNCE_FREEZE,
        500,
        500
    }
};

#define DEM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "MemMap.h"





