/*  BEGIN_FILE_HDR
********************************************************************************
*   File Name       : Os_GenIsr.c
********************************************************************************
*   Project/Product : AUTOSAR BSW PROJECT
*   Title           : OS module configuration File
*   Author          : Hirain
********************************************************************************
*   Description     : OS module configuration File
*
********************************************************************************
*   Limitations     : None
*
********************************************************************************
*
********************************************************************************
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------  ----------   ---------------
*   V1.0.0_3.5.5_AZ240046       27/03/2024    Eas           N/A          N/A
*
********************************************************************************
* END_FILE_HDR*/

#include "Os_Internal.h"

/*****************************************************************************
* General QAC Suppression
******************************************************************************/
/*PRQA S 0862 EOF*/
/*
The code segment like:

#define XXX
#include "Os_MemMap.h"

is a part of AUTOSAR specification, but will be an error in PRQA.
*/

/*PRQA S 3112 EOF*/
/*
Many macros encapsulate assembly instructions which be used to operate 
specific registers or function as C code(inline assembly). 
But PRQA can not parse assembly instructions and notice them as errors. 
So we use: 
#if defined(OS_QAC)
    #define macro (number)
#else
    #define macros asm
#endif
in source code and a macro "OS_QAC" in PRQA config to demotion errors.
PRQA notices these fake macros as warning 3112, it has been suppressed here.
*/

/*PRQA S 3408 EOF*/
/*
This warning were caused by assembly instruction macro "OS_PL_ISR_REGIST"
in this file. Refer to "PRQA S 3112 EOF".
*/

/*PRQA S 3200 EOF*/
/*
This warning were caused by inline functions "OsIntc_C2ISRPreProcess" and 
"OsIntc_C1ISRPreProcess" in this file. They do not return values.
*/

/*PRQA S 3120 EOF*/
/*
This warning were caused by nonzero parameters in functions 
"OsIntc_C2ISRPreProcess" and "OsIntc_C1ISRPreProcess" in this file. 
These numbers had been generated by other tool, so it is not necessary 
to use macro here.
*/

/*****************************************************************************
* Generated Isr functions
******************************************************************************/
#define OS_START_SEC_CODE
#include "Os_MemMap.h"


/*
 * when ISR triggered, hw will auto save upplayer context, including global interrupt state and priority ..
 * then global interrupt is disabled by hw, priority is set to pending ISR
 * then,In MACRO ISRCore, lower context saved, and jump to this function
 *
 */
/*C2 ISR */
OS_PL_ISR_REGIST(STM0_ISROsCore0Func, 0, 1)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)0);
    OsSysTimer_ISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(CROSS_OsCore0Func, 0, 7)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)1);
    OsIntc_CrossCoreISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqCAN2SR0Func, 0, 20)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)2);
    ISR_CAN0_Core0_CAN2SR0();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqCAN2SR1Func, 0, 21)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)3);
    ISR_CAN0_Core0_CAN2SR1();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqCAN2SR2Func, 0, 22)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)4);
    ISR_CAN0_Core0_CAN2SR2();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqCAN2SR3Func, 0, 23)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)5);
    ISR_CAN0_Core0_CAN2SR3();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqCAN2SR4Func, 0, 24)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)6);
    ISR_CAN1_Core0_CAN2SR4();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqCAN2SR5Func, 0, 25)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)7);
    ISR_CAN1_Core0_CAN2SR5();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqCAN2SR6Func, 0, 26)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)8);
    ISR_CAN1_Core0_CAN2SR6();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqCAN2SR7Func, 0, 27)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)9);
    ISR_CAN1_Core0_CAN2SR7();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqETHSR2Func, 0, 34)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)10);
    ISR_Core0_ETHSR2();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(Os_IrqETHSR6Func, 0, 33)
{
    OsIntc_C2ISRPreProcess((CoreIdType)0,(ISRType)11);
    ISR_Core0_ETHSR6();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(STM0_ISROsCore1Func, 0, 2)
{
    OsIntc_C2ISRPreProcess((CoreIdType)1,(ISRType)12);
    OsSysTimer_ISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(CROSS_OsCore1Func, 0, 8)
{
    OsIntc_C2ISRPreProcess((CoreIdType)1,(ISRType)13);
    OsIntc_CrossCoreISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(STM0_ISROsCore2Func, 0, 3)
{
    OsIntc_C2ISRPreProcess((CoreIdType)2,(ISRType)14);
    OsSysTimer_ISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(CROSS_OsCore2Func, 0, 9)
{
    OsIntc_C2ISRPreProcess((CoreIdType)2,(ISRType)15);
    OsIntc_CrossCoreISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(STM0_ISROsCore3Func, 0, 4)
{
    OsIntc_C2ISRPreProcess((CoreIdType)3,(ISRType)16);
    OsSysTimer_ISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(CROSS_OsCore3Func, 0, 10)
{
    OsIntc_C2ISRPreProcess((CoreIdType)3,(ISRType)17);
    OsIntc_CrossCoreISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(STM0_ISROsCore4Func, 0, 5)
{
    OsIntc_C2ISRPreProcess((CoreIdType)4,(ISRType)18);
    OsSysTimer_ISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(CROSS_OsCore4Func, 0, 11)
{
    OsIntc_C2ISRPreProcess((CoreIdType)4,(ISRType)19);
    OsIntc_CrossCoreISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(STM0_ISROsCore5Func, 0, 6)
{
    OsIntc_C2ISRPreProcess((CoreIdType)5,(ISRType)20);
    OsSysTimer_ISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
OS_PL_ISR_REGIST(CROSS_OsCore5Func, 0, 12)
{
    OsIntc_C2ISRPreProcess((CoreIdType)5,(ISRType)21);
    OsIntc_CrossCoreISR();
    OS_PL_JUMP(&OsIntc_OutISR2);
}
/*C1 ISR */
#define OS_STOP_SEC_CODE
#include "Os_MemMap.h"
