/*  BEGIN_FILE_HDR
********************************************************************************
*   File Name       : Os_Lcfg.c
********************************************************************************
*   Project/Product : AUTOSAR BSW PROJECT
*   Title           : OS module configuration File
*   Author          : Hirain
********************************************************************************
*   Description     : OS module configuration File
*
********************************************************************************
*   Limitations     : None
*
********************************************************************************
*
********************************************************************************
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------  ----------   ---------------
*   V1.0.2_3.5.5_AZ240046       09/05/2024    Eas           N/A          N/A
*
********************************************************************************
* END_FILE_HDR*/


/*****************************************************************************
* files include
******************************************************************************/
#include "Os_Internal.h"



/*****************************************************************************
* General QAC Suppression
******************************************************************************/
/*PRQA S 0306 EOF*/
/*
Symbols like "__OS_OsTask1_DATA_start" come from linker and object files.
To use them as value of memory address, such cast or convert is unavoidably.
*/

/*PRQA S 0862 EOF*/
/*
The code segment like:

#define XXX
#include "Os_MemMap.h"

is a part of AUTOSAR specification, but will be an error in PRQA.
*/

/*PRQA S 3132 EOF*/
/*
This warning were caused by nonzero parameters for array size in this file. 
These numbers had been generated by other tool, so it is not necessary 
to use macro here.
*/

/*PRQA S 3211,3408 EOF*/
/*
There are global variables which were defined here to be used in other files.
*/

/*****************************************************************************
* Generated Task and ISR Stacks
******************************************************************************/

#define OS_START_SEC_OS_STACK_CORE0
#include "Os_MemMap.h"

STATIC Os_uint32 Os_TaskStack_OsTask_Core0_InitTask[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core0_Bsw_5ms[512];
STATIC Os_uint32 Os_TaskStack_OsTask_Core0_App_10ms[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core0_BswWdgM_1ms[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core0_App_InitTask[128];
STATIC Os_uint32 Os_TaskStack_TaskIdle0[256];
STATIC Os_uint32 Os_IsrStack_STM0_ISROsCore0[256];
STATIC Os_uint32 Os_IsrStack_CROSS_OsCore0[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqCAN2SR0[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqCAN2SR1[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqCAN2SR2[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqCAN2SR3[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqCAN2SR4[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqCAN2SR5[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqCAN2SR6[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqCAN2SR7[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqETHSR2[256];
STATIC Os_uint32 Os_IsrStack_Os_IrqETHSR6[256];
#define OS_STOP_SEC_OS_STACK_CORE0
#include "Os_MemMap.h"

#define OS_START_SEC_OS_STACK_CORE1
#include "Os_MemMap.h"

STATIC Os_uint32 Os_TaskStack_OsTask_Core1_Bsw_10ms[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core1_InitTask[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core1_App_10ms[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core1_App_InitTask[128];
STATIC Os_uint32 Os_TaskStack_TaskIdle1[256];
STATIC Os_uint32 Os_IsrStack_STM0_ISROsCore1[256];
STATIC Os_uint32 Os_IsrStack_CROSS_OsCore1[256];
#define OS_STOP_SEC_OS_STACK_CORE1
#include "Os_MemMap.h"

#define OS_START_SEC_OS_STACK_CORE2
#include "Os_MemMap.h"

STATIC Os_uint32 Os_TaskStack_OsTask_Core2_Bsw_10ms[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core2_InitTask[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core2_App_10ms[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core2_App_40ms[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core2_App_1ms[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core2_App_5ms[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core2_App_1s[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core2_App_InitTask[128];
STATIC Os_uint32 Os_TaskStack_TaskIdle2[256];
STATIC Os_uint32 Os_IsrStack_STM0_ISROsCore2[256];
STATIC Os_uint32 Os_IsrStack_CROSS_OsCore2[256];
#define OS_STOP_SEC_OS_STACK_CORE2
#include "Os_MemMap.h"

#define OS_START_SEC_OS_STACK_CORE3
#include "Os_MemMap.h"

STATIC Os_uint32 Os_TaskStack_OsTask_Core3_Bsw_10ms[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core3_InitTask[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core3_App_10ms[2560];
STATIC Os_uint32 Os_TaskStack_OsTask_Core3_App_20ms[5120];
STATIC Os_uint32 Os_TaskStack_OsTask_Core3_App_40ms[2560];
STATIC Os_uint32 Os_TaskStack_OsTask_Core3_App_InitTask[128];
STATIC Os_uint32 Os_TaskStack_TaskIdle3[256];
STATIC Os_uint32 Os_IsrStack_STM0_ISROsCore3[256];
STATIC Os_uint32 Os_IsrStack_CROSS_OsCore3[256];
#define OS_STOP_SEC_OS_STACK_CORE3
#include "Os_MemMap.h"

#define OS_START_SEC_OS_STACK_CORE4
#include "Os_MemMap.h"

STATIC Os_uint32 Os_TaskStack_OsTask_Core4_Bsw_10ms[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core4_InitTask[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core4_App_10ms[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core4_App_InitTask[128];
STATIC Os_uint32 Os_TaskStack_TaskIdle4[256];
STATIC Os_uint32 Os_IsrStack_STM0_ISROsCore4[256];
STATIC Os_uint32 Os_IsrStack_CROSS_OsCore4[256];
#define OS_STOP_SEC_OS_STACK_CORE4
#include "Os_MemMap.h"

#define OS_START_SEC_OS_STACK_CORE5
#include "Os_MemMap.h"

STATIC Os_uint32 Os_TaskStack_OsTask_Core5_Bsw_10ms[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core5_InitTask[128];
STATIC Os_uint32 Os_TaskStack_OsTask_Core5_App_10ms[256];
STATIC Os_uint32 Os_TaskStack_OsTask_Core5_App_InitTask[128];
STATIC Os_uint32 Os_TaskStack_TaskIdle5[256];
STATIC Os_uint32 Os_IsrStack_STM0_ISROsCore5[256];
STATIC Os_uint32 Os_IsrStack_CROSS_OsCore5[256];
#define OS_STOP_SEC_OS_STACK_CORE5
#include "Os_MemMap.h"

#define OS_START_SEC_VAR_NOINIT_UNSPECIFIED
#include "Os_MemMap.h"


/*PRQA S 3684,3447 ++*/
/*
These symbols come from linker and object files
and be used as pointer or address value.
They do not need to define in C code and do not
have specific size.
*/


/*PRQA S 3684,3447 --*/


#define OS_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#include "Os_MemMap.h"

/*****************************************************************************
* Generated variables
******************************************************************************/


#define OS_START_SEC_VAR_NOINIT_UNSPECIFIED
#include "Os_MemMap.h"

STATIC TaskType Os_TaskQBuf_Core0_Pri0[11];
STATIC Os_TaskQueueCtlType Os_TaskQueCtl_Core0_Pri0;
STATIC TaskType Os_TaskQBuf_Core0_Pri1[10];
STATIC Os_TaskQueueCtlType Os_TaskQueCtl_Core0_Pri1;
STATIC TaskType Os_TaskQBuf_Core0_Pri2[10];
STATIC Os_TaskQueueCtlType Os_TaskQueCtl_Core0_Pri2;
STATIC TaskType Os_TaskQBuf_Core0_Pri3[1];
STATIC TaskType Os_TaskQBuf_Core0_Pri4[1];
STATIC TaskType Os_TaskQBuf_Core1_Pri0[1];
STATIC TaskType Os_TaskQBuf_Core1_Pri1[1];
STATIC TaskType Os_TaskQBuf_Core1_Pri2[10];
STATIC Os_TaskQueueCtlType Os_TaskQueCtl_Core1_Pri2;
STATIC TaskType Os_TaskQBuf_Core1_Pri3[1];
STATIC TaskType Os_TaskQBuf_Core1_Pri4[1];
STATIC TaskType Os_TaskQBuf_Core2_Pri0[1];
STATIC TaskType Os_TaskQBuf_Core2_Pri1[1];
STATIC TaskType Os_TaskQBuf_Core2_Pri2[50];
STATIC Os_TaskQueueCtlType Os_TaskQueCtl_Core2_Pri2;
STATIC TaskType Os_TaskQBuf_Core2_Pri3[1];
STATIC TaskType Os_TaskQBuf_Core2_Pri4[1];
STATIC TaskType Os_TaskQBuf_Core3_Pri0[1];
STATIC TaskType Os_TaskQBuf_Core3_Pri1[1];
STATIC TaskType Os_TaskQBuf_Core3_Pri2[30];
STATIC Os_TaskQueueCtlType Os_TaskQueCtl_Core3_Pri2;
STATIC TaskType Os_TaskQBuf_Core3_Pri3[1];
STATIC TaskType Os_TaskQBuf_Core3_Pri4[1];
STATIC TaskType Os_TaskQBuf_Core4_Pri0[1];
STATIC TaskType Os_TaskQBuf_Core4_Pri1[1];
STATIC TaskType Os_TaskQBuf_Core4_Pri2[10];
STATIC Os_TaskQueueCtlType Os_TaskQueCtl_Core4_Pri2;
STATIC TaskType Os_TaskQBuf_Core4_Pri3[1];
STATIC TaskType Os_TaskQBuf_Core4_Pri4[1];
STATIC TaskType Os_TaskQBuf_Core5_Pri0[1];
STATIC TaskType Os_TaskQBuf_Core5_Pri1[1];
STATIC TaskType Os_TaskQBuf_Core5_Pri2[10];
STATIC Os_TaskQueueCtlType Os_TaskQueCtl_Core5_Pri2;
STATIC TaskType Os_TaskQBuf_Core5_Pri3[1];
STATIC TaskType Os_TaskQBuf_Core5_Pri4[1];
STATIC VAR(ISRType, OS_VAR) Os_NestIsrID_Core0[12];
STATIC VAR(ISRType, OS_VAR) Os_NestIsrID_Core1[2];
STATIC VAR(ISRType, OS_VAR) Os_NestIsrID_Core2[2];
STATIC VAR(ISRType, OS_VAR) Os_NestIsrID_Core3[2];
STATIC VAR(ISRType, OS_VAR) Os_NestIsrID_Core4[2];
STATIC VAR(ISRType, OS_VAR) Os_NestIsrID_Core5[2];
STATIC Os_CounterTreeQueEleType Os_AlarmQue_SystemCounterOsCore0_0[3];
STATIC Os_CounterTreeQueEleType Os_AlarmQue_SystemCounterOsCore1_1[2];
STATIC Os_CounterTreeQueEleType Os_AlarmQue_SystemCounterOsCore2_2[6];
STATIC Os_CounterTreeQueEleType Os_AlarmQue_SystemCounterOsCore3_3[4];
STATIC Os_CounterTreeQueEleType Os_AlarmQue_SystemCounterOsCore4_4[2];
STATIC Os_CounterTreeQueEleType Os_AlarmQue_SystemCounterOsCore5_5[2];
STATIC Os_uint32 Os_TaskPriReadyTbl_Line_OsCore0;
STATIC Os_uint32 Os_TaskPriReadyTbl_OsCore0[1];
STATIC Os_uint32 Os_TaskPriReadyTbl_Line_OsCore1;
STATIC Os_uint32 Os_TaskPriReadyTbl_OsCore1[1];
STATIC Os_uint32 Os_TaskPriReadyTbl_Line_OsCore2;
STATIC Os_uint32 Os_TaskPriReadyTbl_OsCore2[1];
STATIC Os_uint32 Os_TaskPriReadyTbl_Line_OsCore3;
STATIC Os_uint32 Os_TaskPriReadyTbl_OsCore3[1];
STATIC Os_uint32 Os_TaskPriReadyTbl_Line_OsCore4;
STATIC Os_uint32 Os_TaskPriReadyTbl_OsCore4[1];
STATIC Os_uint32 Os_TaskPriReadyTbl_Line_OsCore5;
STATIC Os_uint32 Os_TaskPriReadyTbl_OsCore5[1];

#define OS_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#include "Os_MemMap.h"

#define OS_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Os_MemMap.h"

/*****************************************************************************
* Task Cfg related
******************************************************************************/
CONST(Os_TaskCfgType, OS_CONST) Os_TaskCfg[OS_TASK_NUMBER] = 
{
    {
        &Os_TaskStack_OsTask_Core0_InitTask[0],
        &Os_TaskStack_OsTask_Core0_InitTask[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (Os_boolean)OS_FALSE,
        (TaskType)0,
        (Os_uint8)1,
        (Os_PrioType)0,
        (Os_boolean)OS_TRUE,
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (TaskType)0,
        &OsTask_Core0_InitTaskFunc
    },
    {
        &Os_TaskStack_OsTask_Core0_Bsw_5ms[0],
        &Os_TaskStack_OsTask_Core0_Bsw_5ms[512],/* pop down makes pointer to the smaller.*/
        (Os_uint16)512,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)1,
        (Os_uint8)10,
        (Os_PrioType)1,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (TaskType)1,
        &OsTask_Core0_Bsw_5msFunc
    },
    {
        &Os_TaskStack_OsTask_Core0_App_10ms[0],
        &Os_TaskStack_OsTask_Core0_App_10ms[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)2,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (TaskType)2,
        &OsTask_Core0_App_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core0_BswWdgM_1ms[0],
        &Os_TaskStack_OsTask_Core0_BswWdgM_1ms[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)3,
        (Os_uint8)10,
        (Os_PrioType)0,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (TaskType)3,
        &OsTask_Core0_BswWdgM_1msFunc
    },
    {
        &Os_TaskStack_OsTask_Core0_App_InitTask[0],
        &Os_TaskStack_OsTask_Core0_App_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)4,
        (Os_uint8)1,
        (Os_PrioType)3,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (TaskType)4,
        &OsTask_Core0_App_InitTaskFunc
    },
    {
        &Os_TaskStack_TaskIdle0[0],
        &Os_TaskStack_TaskIdle0[256],
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)5,
        (Os_uint8)1,
        (Os_PrioType)4,
        (Os_boolean)OS_TRUE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (Os_ApplicationMaskType)OS_APP_ALL_MASK,
        (CoreIdType)0,
        (TaskType)51,
        &TaskIdleCore0Func 
    },
    {
        &Os_TaskStack_OsTask_Core1_Bsw_10ms[0],
        &Os_TaskStack_OsTask_Core1_Bsw_10ms[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_TRUE,
        (TaskType)6,
        (Os_uint8)1,
        (Os_PrioType)1,
        (Os_boolean)OS_FALSE,
        (ApplicationType)1,
        (Os_ApplicationMaskType)0x2,
        (CoreIdType)1,
        (TaskType)0,
        &OsTask_Core1_Bsw_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core1_InitTask[0],
        &Os_TaskStack_OsTask_Core1_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)7,
        (Os_uint8)1,
        (Os_PrioType)0,
        (Os_boolean)OS_TRUE,
        (ApplicationType)1,
        (Os_ApplicationMaskType)0x3,
        (CoreIdType)1,
        (TaskType)1,
        &OsTask_Core1_InitTaskFunc
    },
    {
        &Os_TaskStack_OsTask_Core1_App_10ms[0],
        &Os_TaskStack_OsTask_Core1_App_10ms[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)8,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)1,
        (Os_ApplicationMaskType)0x2,
        (CoreIdType)1,
        (TaskType)2,
        &OsTask_Core1_App_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core1_App_InitTask[0],
        &Os_TaskStack_OsTask_Core1_App_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)9,
        (Os_uint8)1,
        (Os_PrioType)3,
        (Os_boolean)OS_FALSE,
        (ApplicationType)1,
        (Os_ApplicationMaskType)0x2,
        (CoreIdType)1,
        (TaskType)3,
        &OsTask_Core1_App_InitTaskFunc
    },
    {
        &Os_TaskStack_TaskIdle1[0],
        &Os_TaskStack_TaskIdle1[256],
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)10,
        (Os_uint8)1,
        (Os_PrioType)4,
        (Os_boolean)OS_TRUE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (Os_ApplicationMaskType)OS_APP_ALL_MASK,
        (CoreIdType)1,
        (TaskType)41,
        &TaskIdleCore1Func 
    },
    {
        &Os_TaskStack_OsTask_Core2_Bsw_10ms[0],
        &Os_TaskStack_OsTask_Core2_Bsw_10ms[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_TRUE,
        (TaskType)11,
        (Os_uint8)1,
        (Os_PrioType)1,
        (Os_boolean)OS_FALSE,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (TaskType)0,
        &OsTask_Core2_Bsw_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core2_InitTask[0],
        &Os_TaskStack_OsTask_Core2_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)12,
        (Os_uint8)1,
        (Os_PrioType)0,
        (Os_boolean)OS_TRUE,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x5,
        (CoreIdType)2,
        (TaskType)1,
        &OsTask_Core2_InitTaskFunc
    },
    {
        &Os_TaskStack_OsTask_Core2_App_10ms[0],
        &Os_TaskStack_OsTask_Core2_App_10ms[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)13,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (TaskType)2,
        &OsTask_Core2_App_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core2_App_40ms[0],
        &Os_TaskStack_OsTask_Core2_App_40ms[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)14,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (TaskType)3,
        &OsTask_Core2_App_40msFunc
    },
    {
        &Os_TaskStack_OsTask_Core2_App_1ms[0],
        &Os_TaskStack_OsTask_Core2_App_1ms[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)15,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (TaskType)4,
        &OsTask_Core2_App_1msFunc
    },
    {
        &Os_TaskStack_OsTask_Core2_App_5ms[0],
        &Os_TaskStack_OsTask_Core2_App_5ms[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)16,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (TaskType)5,
        &OsTask_Core2_App_5msFunc
    },
    {
        &Os_TaskStack_OsTask_Core2_App_1s[0],
        &Os_TaskStack_OsTask_Core2_App_1s[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)17,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (TaskType)6,
        &OsTask_Core2_App_1sFunc
    },
    {
        &Os_TaskStack_OsTask_Core2_App_InitTask[0],
        &Os_TaskStack_OsTask_Core2_App_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)18,
        (Os_uint8)1,
        (Os_PrioType)3,
        (Os_boolean)OS_FALSE,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (TaskType)7,
        &OsTask_Core2_App_InitTaskFunc
    },
    {
        &Os_TaskStack_TaskIdle2[0],
        &Os_TaskStack_TaskIdle2[256],
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)19,
        (Os_uint8)1,
        (Os_PrioType)4,
        (Os_boolean)OS_TRUE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (Os_ApplicationMaskType)OS_APP_ALL_MASK,
        (CoreIdType)2,
        (TaskType)81,
        &TaskIdleCore2Func 
    },
    {
        &Os_TaskStack_OsTask_Core3_Bsw_10ms[0],
        &Os_TaskStack_OsTask_Core3_Bsw_10ms[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_TRUE,
        (TaskType)20,
        (Os_uint8)1,
        (Os_PrioType)1,
        (Os_boolean)OS_FALSE,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (TaskType)0,
        &OsTask_Core3_Bsw_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core3_InitTask[0],
        &Os_TaskStack_OsTask_Core3_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)21,
        (Os_uint8)1,
        (Os_PrioType)0,
        (Os_boolean)OS_TRUE,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x9,
        (CoreIdType)3,
        (TaskType)1,
        &OsTask_Core3_InitTaskFunc
    },
    {
        &Os_TaskStack_OsTask_Core3_App_10ms[0],
        &Os_TaskStack_OsTask_Core3_App_10ms[2560],/* pop down makes pointer to the smaller.*/
        (Os_uint16)2560,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)22,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (TaskType)2,
        &OsTask_Core3_App_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core3_App_20ms[0],
        &Os_TaskStack_OsTask_Core3_App_20ms[5120],/* pop down makes pointer to the smaller.*/
        (Os_uint16)5120,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)23,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (TaskType)3,
        &OsTask_Core3_App_20msFunc
    },
    {
        &Os_TaskStack_OsTask_Core3_App_40ms[0],
        &Os_TaskStack_OsTask_Core3_App_40ms[2560],/* pop down makes pointer to the smaller.*/
        (Os_uint16)2560,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)24,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (TaskType)4,
        &OsTask_Core3_App_40msFunc
    },
    {
        &Os_TaskStack_OsTask_Core3_App_InitTask[0],
        &Os_TaskStack_OsTask_Core3_App_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)25,
        (Os_uint8)1,
        (Os_PrioType)3,
        (Os_boolean)OS_FALSE,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (TaskType)5,
        &OsTask_Core3_App_InitTaskFunc
    },
    {
        &Os_TaskStack_TaskIdle3[0],
        &Os_TaskStack_TaskIdle3[256],
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)26,
        (Os_uint8)1,
        (Os_PrioType)4,
        (Os_boolean)OS_TRUE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (Os_ApplicationMaskType)OS_APP_ALL_MASK,
        (CoreIdType)3,
        (TaskType)61,
        &TaskIdleCore3Func 
    },
    {
        &Os_TaskStack_OsTask_Core4_Bsw_10ms[0],
        &Os_TaskStack_OsTask_Core4_Bsw_10ms[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_TRUE,
        (TaskType)27,
        (Os_uint8)1,
        (Os_PrioType)1,
        (Os_boolean)OS_FALSE,
        (ApplicationType)4,
        (Os_ApplicationMaskType)0x10,
        (CoreIdType)4,
        (TaskType)0,
        &OsTask_Core4_Bsw_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core4_InitTask[0],
        &Os_TaskStack_OsTask_Core4_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)28,
        (Os_uint8)1,
        (Os_PrioType)0,
        (Os_boolean)OS_TRUE,
        (ApplicationType)4,
        (Os_ApplicationMaskType)0x11,
        (CoreIdType)4,
        (TaskType)1,
        &OsTask_Core4_InitTaskFunc
    },
    {
        &Os_TaskStack_OsTask_Core4_App_10ms[0],
        &Os_TaskStack_OsTask_Core4_App_10ms[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)29,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)4,
        (Os_ApplicationMaskType)0x10,
        (CoreIdType)4,
        (TaskType)2,
        &OsTask_Core4_App_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core4_App_InitTask[0],
        &Os_TaskStack_OsTask_Core4_App_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)30,
        (Os_uint8)1,
        (Os_PrioType)3,
        (Os_boolean)OS_FALSE,
        (ApplicationType)4,
        (Os_ApplicationMaskType)0x10,
        (CoreIdType)4,
        (TaskType)3,
        &OsTask_Core4_App_InitTaskFunc
    },
    {
        &Os_TaskStack_TaskIdle4[0],
        &Os_TaskStack_TaskIdle4[256],
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)31,
        (Os_uint8)1,
        (Os_PrioType)4,
        (Os_boolean)OS_TRUE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (Os_ApplicationMaskType)OS_APP_ALL_MASK,
        (CoreIdType)4,
        (TaskType)41,
        &TaskIdleCore4Func 
    },
    {
        &Os_TaskStack_OsTask_Core5_Bsw_10ms[0],
        &Os_TaskStack_OsTask_Core5_Bsw_10ms[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_TRUE,
        (TaskType)32,
        (Os_uint8)1,
        (Os_PrioType)1,
        (Os_boolean)OS_FALSE,
        (ApplicationType)5,
        (Os_ApplicationMaskType)0x20,
        (CoreIdType)5,
        (TaskType)0,
        &OsTask_Core5_Bsw_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core5_InitTask[0],
        &Os_TaskStack_OsTask_Core5_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)33,
        (Os_uint8)1,
        (Os_PrioType)0,
        (Os_boolean)OS_TRUE,
        (ApplicationType)5,
        (Os_ApplicationMaskType)0x21,
        (CoreIdType)5,
        (TaskType)1,
        &OsTask_Core5_InitTaskFunc
    },
    {
        &Os_TaskStack_OsTask_Core5_App_10ms[0],
        &Os_TaskStack_OsTask_Core5_App_10ms[256],/* pop down makes pointer to the smaller.*/
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)34,
        (Os_uint8)10,
        (Os_PrioType)2,
        (Os_boolean)OS_FALSE,
        (ApplicationType)5,
        (Os_ApplicationMaskType)0x20,
        (CoreIdType)5,
        (TaskType)2,
        &OsTask_Core5_App_10msFunc
    },
    {
        &Os_TaskStack_OsTask_Core5_App_InitTask[0],
        &Os_TaskStack_OsTask_Core5_App_InitTask[128],/* pop down makes pointer to the smaller.*/
        (Os_uint16)128,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)35,
        (Os_uint8)1,
        (Os_PrioType)3,
        (Os_boolean)OS_FALSE,
        (ApplicationType)5,
        (Os_ApplicationMaskType)0x20,
        (CoreIdType)5,
        (TaskType)3,
        &OsTask_Core5_App_InitTaskFunc
    },
    {
        &Os_TaskStack_TaskIdle5[0],
        &Os_TaskStack_TaskIdle5[256],
        (Os_uint16)256,
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (TaskType)36,
        (Os_uint8)1,
        (Os_PrioType)4,
        (Os_boolean)OS_TRUE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (Os_ApplicationMaskType)OS_APP_ALL_MASK,
        (CoreIdType)5,
        (TaskType)41,
        &TaskIdleCore5Func 
    }
};


STATIC CONST(Os_TaskQueCfgType, OS_CONST) Os_TaskQueCfgCore0[5]=
{
    {
        &Os_TaskQueCtl_Core0_Pri0,
        11,
        Os_TaskQBuf_Core0_Pri0
    },
    {
        &Os_TaskQueCtl_Core0_Pri1,
        10,
        Os_TaskQBuf_Core0_Pri1
    },
    {
        &Os_TaskQueCtl_Core0_Pri2,
        10,
        Os_TaskQBuf_Core0_Pri2
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core0_Pri3
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core0_Pri4
    }
};
STATIC CONST(Os_TaskQueCfgType, OS_CONST) Os_TaskQueCfgCore1[5]=
{
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core1_Pri0
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core1_Pri1
    },
    {
        &Os_TaskQueCtl_Core1_Pri2,
        10,
        Os_TaskQBuf_Core1_Pri2
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core1_Pri3
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core1_Pri4
    }
};
STATIC CONST(Os_TaskQueCfgType, OS_CONST) Os_TaskQueCfgCore2[5]=
{
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core2_Pri0
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core2_Pri1
    },
    {
        &Os_TaskQueCtl_Core2_Pri2,
        50,
        Os_TaskQBuf_Core2_Pri2
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core2_Pri3
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core2_Pri4
    }
};
STATIC CONST(Os_TaskQueCfgType, OS_CONST) Os_TaskQueCfgCore3[5]=
{
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core3_Pri0
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core3_Pri1
    },
    {
        &Os_TaskQueCtl_Core3_Pri2,
        30,
        Os_TaskQBuf_Core3_Pri2
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core3_Pri3
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core3_Pri4
    }
};
STATIC CONST(Os_TaskQueCfgType, OS_CONST) Os_TaskQueCfgCore4[5]=
{
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core4_Pri0
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core4_Pri1
    },
    {
        &Os_TaskQueCtl_Core4_Pri2,
        10,
        Os_TaskQBuf_Core4_Pri2
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core4_Pri3
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core4_Pri4
    }
};
STATIC CONST(Os_TaskQueCfgType, OS_CONST) Os_TaskQueCfgCore5[5]=
{
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core5_Pri0
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core5_Pri1
    },
    {
        &Os_TaskQueCtl_Core5_Pri2,
        10,
        Os_TaskQBuf_Core5_Pri2
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core5_Pri3
    },
    {
        NULL_PTR,
        1,
        Os_TaskQBuf_Core5_Pri4
    }
};
/*****************************************************************************
* ISR Cfg related
******************************************************************************/
CONST(Os_ISRCfgType, OS_CONST) Os_ISRCfg[OS_ISR_NUMBER] =
{
    {
        &Os_IsrStack_STM0_ISROsCore0[0],
        &Os_IsrStack_STM0_ISROsCore0[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)0,
        (Os_PrioType)1,
        (Os_uint16)192
    },
    {
        &Os_IsrStack_CROSS_OsCore0[0],
        &Os_IsrStack_CROSS_OsCore0[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)0,
        (Os_PrioType)7,
        (Os_uint16)628
    },
    {
        &Os_IsrStack_Os_IrqCAN2SR0[0],
        &Os_IsrStack_Os_IrqCAN2SR0[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)20,
        (Os_uint16)396
    },
    {
        &Os_IsrStack_Os_IrqCAN2SR1[0],
        &Os_IsrStack_Os_IrqCAN2SR1[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)21,
        (Os_uint16)397
    },
    {
        &Os_IsrStack_Os_IrqCAN2SR2[0],
        &Os_IsrStack_Os_IrqCAN2SR2[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)22,
        (Os_uint16)398
    },
    {
        &Os_IsrStack_Os_IrqCAN2SR3[0],
        &Os_IsrStack_Os_IrqCAN2SR3[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)23,
        (Os_uint16)399
    },
    {
        &Os_IsrStack_Os_IrqCAN2SR4[0],
        &Os_IsrStack_Os_IrqCAN2SR4[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)24,
        (Os_uint16)400
    },
    {
        &Os_IsrStack_Os_IrqCAN2SR5[0],
        &Os_IsrStack_Os_IrqCAN2SR5[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)25,
        (Os_uint16)401
    },
    {
        &Os_IsrStack_Os_IrqCAN2SR6[0],
        &Os_IsrStack_Os_IrqCAN2SR6[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)26,
        (Os_uint16)402
    },
    {
        &Os_IsrStack_Os_IrqCAN2SR7[0],
        &Os_IsrStack_Os_IrqCAN2SR7[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)27,
        (Os_uint16)403
    },
    {
        &Os_IsrStack_Os_IrqETHSR2[0],
        &Os_IsrStack_Os_IrqETHSR2[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)34,
        (Os_uint16)354
    },
    {
        &Os_IsrStack_Os_IrqETHSR6[0],
        &Os_IsrStack_Os_IrqETHSR6[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)0,
        (CoreIdType)0,
        (Os_PrioType)33,
        (Os_uint16)358
    },
    {
        &Os_IsrStack_STM0_ISROsCore1[0],
        &Os_IsrStack_STM0_ISROsCore1[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)1,
        (Os_PrioType)2,
        (Os_uint16)194
    },
    {
        &Os_IsrStack_CROSS_OsCore1[0],
        &Os_IsrStack_CROSS_OsCore1[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)1,
        (Os_PrioType)8,
        (Os_uint16)629
    },
    {
        &Os_IsrStack_STM0_ISROsCore2[0],
        &Os_IsrStack_STM0_ISROsCore2[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)2,
        (Os_PrioType)3,
        (Os_uint16)196
    },
    {
        &Os_IsrStack_CROSS_OsCore2[0],
        &Os_IsrStack_CROSS_OsCore2[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)2,
        (Os_PrioType)9,
        (Os_uint16)630
    },
    {
        &Os_IsrStack_STM0_ISROsCore3[0],
        &Os_IsrStack_STM0_ISROsCore3[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)3,
        (Os_PrioType)4,
        (Os_uint16)198
    },
    {
        &Os_IsrStack_CROSS_OsCore3[0],
        &Os_IsrStack_CROSS_OsCore3[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)3,
        (Os_PrioType)10,
        (Os_uint16)631
    },
    {
        &Os_IsrStack_STM0_ISROsCore4[0],
        &Os_IsrStack_STM0_ISROsCore4[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)4,
        (Os_PrioType)5,
        (Os_uint16)200
    },
    {
        &Os_IsrStack_CROSS_OsCore4[0],
        &Os_IsrStack_CROSS_OsCore4[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)4,
        (Os_PrioType)11,
        (Os_uint16)632
    },
    {
        &Os_IsrStack_STM0_ISROsCore5[0],
        &Os_IsrStack_STM0_ISROsCore5[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)5,
        (Os_PrioType)6,
        (Os_uint16)202
    },
    {
        &Os_IsrStack_CROSS_OsCore5[0],
        &Os_IsrStack_CROSS_OsCore5[256],
        (Os_uint16)256,
        (Os_boolean)OS_FALSE,
        (ApplicationType)OS_INVALID_OSAPPLICATION,
        (CoreIdType)5,
        (Os_PrioType)12,
        (Os_uint16)633
    }
};

/*****************************************************************************
* OS Application Cfg related
******************************************************************************/
CONST(TaskType, OS_CONST) TaskOf_OsApplication0_Core0[5]=
{
    (TaskType)0,
    (TaskType)1,
    (TaskType)2,
    (TaskType)3,
    (TaskType)4
};
CONST(ISRType, OS_CONST) IsrOf_OsApplication0_Core0[10]=
{
    (ISRType)2,
    (ISRType)3,
    (ISRType)4,
    (ISRType)5,
    (ISRType)6,
    (ISRType)7,
    (ISRType)8,
    (ISRType)9,
    (ISRType)10,
    (ISRType)11
};
CONST(AlarmType, OS_CONST) AlarmOf_OsApplication0_Core0[3]=
{
    (AlarmType)0,
    (AlarmType)1,
    (AlarmType)2
};
CONST(CounterType, OS_CONST) cntOf_OsApplication0_Core0[1]=
{
    (CounterType)0
};
CONST(TaskType, OS_CONST) TaskOf_OsApplication0_Core1[4]=
{
    (TaskType)7,
    (TaskType)8,
    (TaskType)6,
    (TaskType)9
};
CONST(AlarmType, OS_CONST) AlarmOf_OsApplication0_Core1[2]=
{
    (AlarmType)3,
    (AlarmType)4
};
CONST(CounterType, OS_CONST) cntOf_OsApplication0_Core1[1]=
{
    (CounterType)1
};
CONST(TaskType, OS_CONST) TaskOf_OsApplication0_Core2[8]=
{
    (TaskType)12,
    (TaskType)13,
    (TaskType)11,
    (TaskType)14,
    (TaskType)15,
    (TaskType)16,
    (TaskType)17,
    (TaskType)18
};
CONST(AlarmType, OS_CONST) AlarmOf_OsApplication0_Core2[6]=
{
    (AlarmType)5,
    (AlarmType)6,
    (AlarmType)7,
    (AlarmType)8,
    (AlarmType)9,
    (AlarmType)10
};
CONST(CounterType, OS_CONST) cntOf_OsApplication0_Core2[1]=
{
    (CounterType)2
};
CONST(TaskType, OS_CONST) TaskOf_OsApplication0_Core3[6]=
{
    (TaskType)21,
    (TaskType)22,
    (TaskType)20,
    (TaskType)23,
    (TaskType)24,
    (TaskType)25
};
CONST(AlarmType, OS_CONST) AlarmOf_OsApplication0_Core3[4]=
{
    (AlarmType)11,
    (AlarmType)12,
    (AlarmType)13,
    (AlarmType)14
};
CONST(CounterType, OS_CONST) cntOf_OsApplication0_Core3[1]=
{
    (CounterType)3
};
CONST(TaskType, OS_CONST) TaskOf_OsApplication0_Core4[4]=
{
    (TaskType)28,
    (TaskType)29,
    (TaskType)27,
    (TaskType)30
};
CONST(AlarmType, OS_CONST) AlarmOf_OsApplication0_Core4[2]=
{
    (AlarmType)15,
    (AlarmType)16
};
CONST(CounterType, OS_CONST) cntOf_OsApplication0_Core4[1]=
{
    (CounterType)4
};
CONST(TaskType, OS_CONST) TaskOf_OsApplication0_Core5[4]=
{
    (TaskType)33,
    (TaskType)34,
    (TaskType)32,
    (TaskType)35
};
CONST(AlarmType, OS_CONST) AlarmOf_OsApplication0_Core5[2]=
{
    (AlarmType)17,
    (AlarmType)18
};
CONST(CounterType, OS_CONST) cntOf_OsApplication0_Core5[1]=
{
    (CounterType)5
};

CONST(Os_AppCfgType, OS_CONST) Os_AppCfg[OS_APPLICATION_NUMBER] =
{
    {
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (CoreIdType)0,
        (ApplicationType)0,
        TaskOf_OsApplication0_Core0,
        (TaskType)5,
        IsrOf_OsApplication0_Core0,
        (ISRType)10,
        AlarmOf_OsApplication0_Core0,
        (AlarmType)3,
        cntOf_OsApplication0_Core0,
        (CounterType)1
    },
    {
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (CoreIdType)1,
        (ApplicationType)0,
        TaskOf_OsApplication0_Core1,
        (TaskType)4,
        NULL_PTR,
        (ISRType)0,
        AlarmOf_OsApplication0_Core1,
        (AlarmType)2,
        cntOf_OsApplication0_Core1,
        (CounterType)1
    },
    {
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (CoreIdType)2,
        (ApplicationType)0,
        TaskOf_OsApplication0_Core2,
        (TaskType)8,
        NULL_PTR,
        (ISRType)0,
        AlarmOf_OsApplication0_Core2,
        (AlarmType)6,
        cntOf_OsApplication0_Core2,
        (CounterType)1
    },
    {
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (CoreIdType)3,
        (ApplicationType)0,
        TaskOf_OsApplication0_Core3,
        (TaskType)6,
        NULL_PTR,
        (ISRType)0,
        AlarmOf_OsApplication0_Core3,
        (AlarmType)4,
        cntOf_OsApplication0_Core3,
        (CounterType)1
    },
    {
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (CoreIdType)4,
        (ApplicationType)0,
        TaskOf_OsApplication0_Core4,
        (TaskType)4,
        NULL_PTR,
        (ISRType)0,
        AlarmOf_OsApplication0_Core4,
        (AlarmType)2,
        cntOf_OsApplication0_Core4,
        (CounterType)1
    },
    {
        (Os_boolean)OS_TRUE,
        (Os_boolean)OS_FALSE,
        (CoreIdType)5,
        (ApplicationType)0,
        TaskOf_OsApplication0_Core5,
        (TaskType)4,
        NULL_PTR,
        (ISRType)0,
        AlarmOf_OsApplication0_Core5,
        (AlarmType)2,
        cntOf_OsApplication0_Core5,
        (CounterType)1
    }
};


/*****************************************************************************
* Counter Cfg related
******************************************************************************/
CONST(Os_CounterCfgType, OS_CONST) Os_CounterCfg[OS_COUNTER_NUMBER] = 
{
    {
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (CounterType)0,
        {
            (TickType)65535,
            (TickType)1,
            (TickType)1
        },
        (Os_uint32)3,
        Os_AlarmQue_SystemCounterOsCore0_0
    },
    {
        (ApplicationType)1,
        (Os_ApplicationMaskType)0x2,
        (CoreIdType)1,
        (CounterType)0,
        {
            (TickType)65535,
            (TickType)1,
            (TickType)1
        },
        (Os_uint32)2,
        Os_AlarmQue_SystemCounterOsCore1_1
    },
    {
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (CounterType)0,
        {
            (TickType)65535,
            (TickType)1,
            (TickType)1
        },
        (Os_uint32)6,
        Os_AlarmQue_SystemCounterOsCore2_2
    },
    {
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (CounterType)0,
        {
            (TickType)65535,
            (TickType)1,
            (TickType)1
        },
        (Os_uint32)4,
        Os_AlarmQue_SystemCounterOsCore3_3
    },
    {
        (ApplicationType)4,
        (Os_ApplicationMaskType)0x10,
        (CoreIdType)4,
        (CounterType)0,
        {
            (TickType)65535,
            (TickType)1,
            (TickType)1
        },
        (Os_uint32)2,
        Os_AlarmQue_SystemCounterOsCore4_4
    },
    {
        (ApplicationType)5,
        (Os_ApplicationMaskType)0x20,
        (CoreIdType)5,
        (CounterType)0,
        {
            (TickType)65535,
            (TickType)1,
            (TickType)1
        },
        (Os_uint32)2,
        Os_AlarmQue_SystemCounterOsCore5_5
    }
};
/*****************************************************************************
* Alarm Cfg related
******************************************************************************/
CONST(Os_AlarmCfgType, OS_CONST) Os_AlarmCfg[OS_ALARM_NUMBER] =
{
    {
        (TaskType)1,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (AlarmType)0,
        (AlarmType)0,
        (CounterType)0,
        OS_ALARM_TASK
    },
    {
        (TaskType)2,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (AlarmType)1,
        (AlarmType)1,
        (CounterType)0,
        OS_ALARM_TASK
    },
    {
        (TaskType)3,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)0,
        (Os_ApplicationMaskType)0x1,
        (CoreIdType)0,
        (AlarmType)2,
        (AlarmType)2,
        (CounterType)0,
        OS_ALARM_TASK
    },
    {
        (TaskType)8,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)1,
        (Os_ApplicationMaskType)0x2,
        (CoreIdType)1,
        (AlarmType)0,
        (AlarmType)3,
        (CounterType)1,
        OS_ALARM_TASK
    },
    {
        (TaskType)6,
        (EventMaskType)OsTask_Core1_Bsw_10ms_OsEvent_Core1_Bsw_10ms,
        (ApplicationType)1,
        (Os_ApplicationMaskType)0x2,
        (CoreIdType)1,
        (AlarmType)1,
        (AlarmType)4,
        (CounterType)1,
        OS_ALARM_EVENT
    },
    {
        (TaskType)13,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (AlarmType)0,
        (AlarmType)5,
        (CounterType)2,
        OS_ALARM_TASK
    },
    {
        (TaskType)11,
        (EventMaskType)OsTask_Core2_Bsw_10ms_OsEvent_Core2_Bsw_10ms,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (AlarmType)1,
        (AlarmType)6,
        (CounterType)2,
        OS_ALARM_EVENT
    },
    {
        (TaskType)14,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (AlarmType)2,
        (AlarmType)7,
        (CounterType)2,
        OS_ALARM_TASK
    },
    {
        (TaskType)16,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (AlarmType)3,
        (AlarmType)8,
        (CounterType)2,
        OS_ALARM_TASK
    },
    {
        (TaskType)15,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (AlarmType)4,
        (AlarmType)9,
        (CounterType)2,
        OS_ALARM_TASK
    },
    {
        (TaskType)17,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)2,
        (Os_ApplicationMaskType)0x4,
        (CoreIdType)2,
        (AlarmType)5,
        (AlarmType)10,
        (CounterType)2,
        OS_ALARM_TASK
    },
    {
        (TaskType)22,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (AlarmType)0,
        (AlarmType)11,
        (CounterType)3,
        OS_ALARM_TASK
    },
    {
        (TaskType)20,
        (EventMaskType)OsTask_Core3_Bsw_10ms_OsEvent_Core3_Bsw_10ms,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (AlarmType)1,
        (AlarmType)12,
        (CounterType)3,
        OS_ALARM_EVENT
    },
    {
        (TaskType)23,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (AlarmType)2,
        (AlarmType)13,
        (CounterType)3,
        OS_ALARM_TASK
    },
    {
        (TaskType)24,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)3,
        (Os_ApplicationMaskType)0x8,
        (CoreIdType)3,
        (AlarmType)3,
        (AlarmType)14,
        (CounterType)3,
        OS_ALARM_TASK
    },
    {
        (TaskType)29,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)4,
        (Os_ApplicationMaskType)0x10,
        (CoreIdType)4,
        (AlarmType)0,
        (AlarmType)15,
        (CounterType)4,
        OS_ALARM_TASK
    },
    {
        (TaskType)27,
        (EventMaskType)OsTask_Core4_Bsw_10ms_OsEvent_Core4_Bsw_10ms,
        (ApplicationType)4,
        (Os_ApplicationMaskType)0x10,
        (CoreIdType)4,
        (AlarmType)1,
        (AlarmType)16,
        (CounterType)4,
        OS_ALARM_EVENT
    },
    {
        (TaskType)34,
        (EventMaskType)OS_INVALID_EVENT_MASK,
        (ApplicationType)5,
        (Os_ApplicationMaskType)0x20,
        (CoreIdType)5,
        (AlarmType)0,
        (AlarmType)17,
        (CounterType)5,
        OS_ALARM_TASK
    },
    {
        (TaskType)32,
        (EventMaskType)OsTask_Core5_Bsw_10ms_OsEvent_Core5_Bsw_10ms,
        (ApplicationType)5,
        (Os_ApplicationMaskType)0x20,
        (CoreIdType)5,
        (AlarmType)1,
        (AlarmType)18,
        (CounterType)5,
        OS_ALARM_EVENT
    }
};
/*****************************************************************************
* Core Cfg related
******************************************************************************/
CONST(Os_CoreCfgType, OS_CONST) Os_CoreCfg[OS_USED_CORE_NUMBER] =
{
    {
        /*Task*/
        (TaskType)0,/*startTaskId*/
        (TaskType)6,/*taskNum*/
        (TaskType)2,/*autotaskNum*/
        (TaskType)0,/*extendtaskNum*/
        (TaskType)5,/*idleTaskId*/
        (Os_PrioType)5,/*TaskPriNumOfCore*/
        Os_TaskQueCfgCore0,
        {
            &Os_TaskPriReadyTbl_Line_OsCore0,
            Os_TaskPriReadyTbl_OsCore0,
            (Os_uint8)1
        },

        /*Isr*/
        (ISRType)0,
        (ISRType)12,/*c2IsrNum*/
        (ISRType)0,/*c1IsrNum*/
        (ISRType)0,/*sysCntIsrId*/
        (ISRType)1,/*crossIsrId*/
        (Os_PrioType)34,/*topC2IsrPri*/
        Os_NestIsrID_Core0,
        (ISRType)1,

        /*alarm*/
        (AlarmType)0,
        (AlarmType)3,
        (AlarmType)0,



        /*Application*/
        (ApplicationType)0,
        (ApplicationType)1,

        /*counter*/
        (CounterType)0,
        (CounterType)1
    },
    {
        /*Task*/
        (TaskType)6,/*startTaskId*/
        (TaskType)5,/*taskNum*/
        (TaskType)2,/*autotaskNum*/
        (TaskType)1,/*extendtaskNum*/
        (TaskType)10,/*idleTaskId*/
        (Os_PrioType)5,/*TaskPriNumOfCore*/
        Os_TaskQueCfgCore1,
        {
            &Os_TaskPriReadyTbl_Line_OsCore1,
            Os_TaskPriReadyTbl_OsCore1,
            (Os_uint8)1
        },

        /*Isr*/
        (ISRType)12,
        (ISRType)2,/*c2IsrNum*/
        (ISRType)0,/*c1IsrNum*/
        (ISRType)12,/*sysCntIsrId*/
        (ISRType)13,/*crossIsrId*/
        (Os_PrioType)8,/*topC2IsrPri*/
        Os_NestIsrID_Core1,
        (ISRType)1,

        /*alarm*/
        (AlarmType)3,
        (AlarmType)2,
        (AlarmType)0,



        /*Application*/
        (ApplicationType)1,
        (ApplicationType)1,

        /*counter*/
        (CounterType)1,
        (CounterType)1
    },
    {
        /*Task*/
        (TaskType)11,/*startTaskId*/
        (TaskType)9,/*taskNum*/
        (TaskType)2,/*autotaskNum*/
        (TaskType)1,/*extendtaskNum*/
        (TaskType)19,/*idleTaskId*/
        (Os_PrioType)5,/*TaskPriNumOfCore*/
        Os_TaskQueCfgCore2,
        {
            &Os_TaskPriReadyTbl_Line_OsCore2,
            Os_TaskPriReadyTbl_OsCore2,
            (Os_uint8)1
        },

        /*Isr*/
        (ISRType)14,
        (ISRType)2,/*c2IsrNum*/
        (ISRType)0,/*c1IsrNum*/
        (ISRType)14,/*sysCntIsrId*/
        (ISRType)15,/*crossIsrId*/
        (Os_PrioType)9,/*topC2IsrPri*/
        Os_NestIsrID_Core2,
        (ISRType)1,

        /*alarm*/
        (AlarmType)5,
        (AlarmType)6,
        (AlarmType)0,



        /*Application*/
        (ApplicationType)2,
        (ApplicationType)1,

        /*counter*/
        (CounterType)2,
        (CounterType)1
    },
    {
        /*Task*/
        (TaskType)20,/*startTaskId*/
        (TaskType)7,/*taskNum*/
        (TaskType)2,/*autotaskNum*/
        (TaskType)1,/*extendtaskNum*/
        (TaskType)26,/*idleTaskId*/
        (Os_PrioType)5,/*TaskPriNumOfCore*/
        Os_TaskQueCfgCore3,
        {
            &Os_TaskPriReadyTbl_Line_OsCore3,
            Os_TaskPriReadyTbl_OsCore3,
            (Os_uint8)1
        },

        /*Isr*/
        (ISRType)16,
        (ISRType)2,/*c2IsrNum*/
        (ISRType)0,/*c1IsrNum*/
        (ISRType)16,/*sysCntIsrId*/
        (ISRType)17,/*crossIsrId*/
        (Os_PrioType)10,/*topC2IsrPri*/
        Os_NestIsrID_Core3,
        (ISRType)1,

        /*alarm*/
        (AlarmType)11,
        (AlarmType)4,
        (AlarmType)0,



        /*Application*/
        (ApplicationType)3,
        (ApplicationType)1,

        /*counter*/
        (CounterType)3,
        (CounterType)1
    },
    {
        /*Task*/
        (TaskType)27,/*startTaskId*/
        (TaskType)5,/*taskNum*/
        (TaskType)2,/*autotaskNum*/
        (TaskType)1,/*extendtaskNum*/
        (TaskType)31,/*idleTaskId*/
        (Os_PrioType)5,/*TaskPriNumOfCore*/
        Os_TaskQueCfgCore4,
        {
            &Os_TaskPriReadyTbl_Line_OsCore4,
            Os_TaskPriReadyTbl_OsCore4,
            (Os_uint8)1
        },

        /*Isr*/
        (ISRType)18,
        (ISRType)2,/*c2IsrNum*/
        (ISRType)0,/*c1IsrNum*/
        (ISRType)18,/*sysCntIsrId*/
        (ISRType)19,/*crossIsrId*/
        (Os_PrioType)11,/*topC2IsrPri*/
        Os_NestIsrID_Core4,
        (ISRType)1,

        /*alarm*/
        (AlarmType)15,
        (AlarmType)2,
        (AlarmType)0,



        /*Application*/
        (ApplicationType)4,
        (ApplicationType)1,

        /*counter*/
        (CounterType)4,
        (CounterType)1
    },
    {
        /*Task*/
        (TaskType)32,/*startTaskId*/
        (TaskType)5,/*taskNum*/
        (TaskType)2,/*autotaskNum*/
        (TaskType)1,/*extendtaskNum*/
        (TaskType)36,/*idleTaskId*/
        (Os_PrioType)5,/*TaskPriNumOfCore*/
        Os_TaskQueCfgCore5,
        {
            &Os_TaskPriReadyTbl_Line_OsCore5,
            Os_TaskPriReadyTbl_OsCore5,
            (Os_uint8)1
        },

        /*Isr*/
        (ISRType)20,
        (ISRType)2,/*c2IsrNum*/
        (ISRType)0,/*c1IsrNum*/
        (ISRType)20,/*sysCntIsrId*/
        (ISRType)21,/*crossIsrId*/
        (Os_PrioType)12,/*topC2IsrPri*/
        Os_NestIsrID_Core5,
        (ISRType)1,

        /*alarm*/
        (AlarmType)17,
        (AlarmType)2,
        (AlarmType)0,



        /*Application*/
        (ApplicationType)5,
        (ApplicationType)1,

        /*counter*/
        (CounterType)5,
        (CounterType)1
    }
};

#define OS_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Os_MemMap.h"
